#!/usr/bin/env php
<?php

set_time_limit(0);

$app = require_once __DIR__.'/bootstrap.php';

use CiBoulette\Tools\Helper\SecurityEncoderHelper;
use CiBoulette\Tools\Console\ConsoleRunner;

use Symfony\Component\Console\Helper\HelperSet;

$helperSet = new HelperSet(array(
    'encoder' => new SecurityEncoderHelper($app['security.encoder.digest'])
));
 
ConsoleRunner::run($helperSet);

$application = $app['console'];
$application->run();

?>